In [15]:
import numpy as np
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])
np.linalg.lstsq(A, B)


#np.dot(a, X) - B

C:\Users\shpin\AppData\Local\Temp/ipykernel_8292/1333533055.py:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A, B)


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

In [16]:
np.dot(A,[ 1.13919353, -0.90498444, -0.9009803 ])

array([ 0.23020495,  7.03751835, 11.83650984,  6.78328856, 15.21805317])

In [17]:
np.dot(A,[ 1.13919353, -0.90498444, -0.9009803 ])-B

array([-0.76979505,  0.03751835, -0.16349016, -0.21671144,  0.21805317])