In [32]:
import numpy as np
import scipy
import scipy.linalg
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([2, 5, 11])
Q, R = np.linalg.qr(A)

print(np.linalg.det(A))

print(A)
print(Q)
print(R)





6.66133814775094e-16
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.77635684e-15]]


In [25]:
print(np.dot(Q, R))
print(np.dot(np.transpose(Q), Q))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 1.00000000e+00 -5.55111512e-16 -2.77555756e-16]
 [-5.55111512e-16  1.00000000e+00  5.68989300e-16]
 [-2.77555756e-16  5.68989300e-16  1.00000000e+00]]


In [26]:
R1 = R[:2, :2]
R1

array([[-8.1240384 , -9.6011363 ],
       [ 0.        ,  0.90453403]])

In [27]:
B1 = np.dot(np.transpose(Q), B)[:2]
B1

array([-27.326311  ,   1.80906807])

In [28]:
X1 = np.linalg.solve(R1, B1)
X1

array([1., 2.])

In [29]:
X = np.append(X1, 0)
print(X)
np.linalg.norm(X)

[1. 2. 0.]


2.236067977499794

In [30]:
np.linalg.norm(np.dot(A, X) - B)

2.4494897427831774