In [32]:
import numpy as np
from scipy.linalg import solve
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[2, 5, 8]])
c = np.concatenate((a, b.T), axis=1)
print(c)
np.linalg.matrix_rank(a, 0.0001), np.linalg.matrix_rank(c, 0.0001)



[[1 2 3 2]
 [4 5 6 5]
 [7 8 9 8]]


(2, 2)

array([-0.76979505,  0.03751835, -0.16349016, -0.21671144,  0.21805317])