In [23]:
import numpy as np
import scipy
import scipy.linalg
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
#A = np.array([ [7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6]])
print(A)
P, L, U = scipy.linalg.lu(A)
print(np.linalg.det(A))
#P = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print(P)
print(L)
print(U)

print(np.dot(P, A)-np.dot(L, U))



[[ 1  2  3]
 [ 2 16 21]
 [ 4 28 73]]
432.00000000000017
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
[[ -2. -12. -52.]
 [  3.  26.  70.]
 [ -1. -14. -18.]]
